package t3;

import android.os.Parcel;
import kotlin.NotImplementedError;
import org.jetbrains.annotations.NotNull;
/* compiled from: Parceler.kt */
/* loaded from: classes7.dex */
public interface b<T> {

    /* compiled from: Parceler.kt */
    /* loaded from: classes7.dex */
    public static final class a {
        @NotNull
        public static <T> T[] a(@NotNull b<T> bVar, int i4) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    void a(T t4, @NotNull Parcel parcel, int i4);

    T b(@NotNull Parcel parcel);

    @NotNull
    T[] newArray(int i4);
}
