package r3;

import android.os.Parcel;
import kotlin.NotImplementedError;
import org.jetbrains.annotations.NotNull;
/* compiled from: Parceler.kt */
/* loaded from: classes6.dex */
public interface a<T> {

    /* compiled from: Parceler.kt */
    /* renamed from: r3.a$a  reason: collision with other inner class name */
    /* loaded from: classes6.dex */
    public static final class C0808a {
        @NotNull
        public static <T> T[] a(@NotNull a<T> aVar, int i4) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    void a(T t4, @NotNull Parcel parcel, int i4);

    T b(@NotNull Parcel parcel);

    @NotNull
    T[] newArray(int i4);
}
