package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.InvokeBy;
import com.kwad.components.core.video.a.d;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.ae;
import com.kwad.components.core.webview.jshandler.af;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.al;
import com.kwad.components.core.webview.jshandler.am;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.aq;
import com.kwad.components.core.webview.jshandler.ar;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.ax;
import com.kwad.components.core.webview.jshandler.ba;
import com.kwad.components.core.webview.jshandler.bb;
import com.kwad.components.core.webview.jshandler.bc;
import com.kwad.components.core.webview.jshandler.be;
import com.kwad.components.core.webview.jshandler.c;
import com.kwad.components.core.webview.jshandler.d;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.j;
import com.kwad.components.core.webview.jshandler.k;
import com.kwad.components.core.webview.jshandler.o;
import com.kwad.components.core.webview.jshandler.s;
import com.kwad.components.core.webview.jshandler.t;
import com.kwad.components.core.webview.jshandler.w;
import com.kwad.components.core.webview.tachikoma.a.h;
import com.kwad.components.core.webview.tachikoma.a.u;
import com.kwad.components.core.webview.tachikoma.a.x;
import com.kwad.sdk.i.a;
import com.kwad.sdk.kgeo.KGeoInfo;
/* loaded from: classes5.dex */
public final class cn {
    @InvokeBy(invokerClass = fr.class, methodId = "registerHolder")
    public static void Ej() {
        fr.Ek().put(av.a.class, new kv());
        fr.Ek().put(ai.a.class, new et());
        fr.Ek().put(as.a.class, new bd());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.v.class, new kj());
        fr.Ek().put(a.c.class, new gs());
        fr.Ek().put(a.b.class, new im());
        fr.Ek().put(an.a.class, new fn());
        fr.Ek().put(d.b.class, new kp());
        fr.Ek().put(f.a.class, new eh());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.w.class, new km());
        fr.Ek().put(com.kwad.components.core.n.c.b.class, new gz());
        fr.Ek().put(t.b.class, new jm());
        fr.Ek().put(KGeoInfo.class, new fs());
        fr.Ek().put(as.b.class, new be());
        fr.Ek().put(af.a.class, new hr());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.b.class, new bf());
        fr.Ek().put(ba.a.class, new ku());
        fr.Ek().put(an.b.class, new fo());
        fr.Ek().put(at.a.class, new bm());
        fr.Ek().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new ab());
        fr.Ek().put(ah.a.class, new kk());
        fr.Ek().put(com.kwad.sdk.a.a.a.a.class, new fe());
        fr.Ek().put(g.a.class, new ei());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.c.class, new bj());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.m.class, new gm());
        fr.Ek().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ft());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.s.class, new is());
        fr.Ek().put(c.b.class, new ew());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.a.class, new n());
        fr.Ek().put(ae.a.class, new hq());
        fr.Ek().put(a.C0477a.class, new db());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.g.class, new ce());
        fr.Ek().put(WebCardVideoPositionHandler.VideoPosition.class, new ks());
        fr.Ek().put(d.a.class, new ko());
        fr.Ek().put(com.kwad.components.core.page.b.a.class, new fw());
        fr.Ek().put(w.a.class, new u());
        fr.Ek().put(u.b.class, new jg());
        fr.Ek().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new z());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.j.class, new fp());
        fr.Ek().put(ar.a.class, new ba());
        fr.Ek().put(bb.a.class, new jw());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.d.class, new bl());
        fr.Ek().put(com.kwad.components.core.webview.a.b.class, new ha());
        fr.Ek().put(com.kwad.components.core.webview.a.c.class, new hc());
        fr.Ek().put(ax.a.class, new fz());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.u.class, new jf());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.e.class, new bv());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.y.class, new kt());
        fr.Ek().put(al.a.class, new cq());
        fr.Ek().put(aq.a.class, new hh());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.i.class, new em());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.x.class, new kq());
        fr.Ek().put(x.a.class, new bh());
        fr.Ek().put(a.C0536a.class, new il());
        fr.Ek().put(bc.a.class, new er());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.l.class, new fx());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.n.class, new hb());
        fr.Ek().put(k.b.class, new fd());
        fr.Ek().put(s.a.class, new jq());
        fr.Ek().put(h.a.class, new ej());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.f.class, new cb());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.h.class, new cu());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.q.class, new ip());
        fr.Ek().put(com.kwad.components.core.n.c.d.class, new ki());
        fr.Ek().put(e.a.class, new eg());
        fr.Ek().put(k.a.class, new fc());
        fr.Ek().put(h.b.class, new ek());
        fr.Ek().put(a.C0478a.class, new ai());
        fr.Ek().put(o.a.class, new gk());
        fr.Ek().put(a.b.class, new de());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.o.class, new hf());
        fr.Ek().put(am.b.class, new eo());
        fr.Ek().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new aa());
        fr.Ek().put(be.a.class, new fq());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.r.class, new ir());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.p.class, new hn());
        fr.Ek().put(com.kwad.components.core.webview.tachikoma.b.t.class, new it());
        fr.Ek().put(com.kwad.components.core.k.a.class, new s());
        fr.Ek().put(h.b.class, new hp());
        fr.Ek().put(j.a.class, new el());
        fr.Ek().put(d.a.class, new ef());
    }
}
