package com.kwad.sdk.core.config;

import com.bytedance.sdk.openadsdk.downloadnew.core.TTDownloadField;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.kwad.sdk.core.config.item.r;
import java.util.ArrayList;
/* loaded from: classes5.dex */
public final class c {
    public static k arB = new k("batchReportCatchLimit", 20);
    public static k arC = new k("exceptionCollectorSwitch", 1);
    public static k arD = new k("catchExceptionReportSwitch", 1);
    public static k arE = new k("mediaPlayerLogReport", 0);
    public static k arF = new k("didCopySwitch", 1);
    public static k arG = new k("enableHodor", 0);
    public static k arH = new k("speedLimitSwitch", 1);
    public static k arI = new k("speedLimitThreshold", 200);
    public static k arJ = new k("ksNativeAdCustomSwitch", 0);
    public static k arK = new k("compoAndSoThreadPoolCoreSize", 0);
    public static k arL = new k("forceActivateAfterInstalled", 0);
    public static k arM = new k("spliceVideoInteractionType", 0);
    public static k arN = new k("feedLoadOptimizeType", 0);
    public static k arO = new k("feedLoadOptimizeExternalEnable", 0);
    public static k arP = new k("nativeAdSlideClickDisable", 0);
    public static k arQ = new k("interstitialAdLoadProcessChange", 0);
    public static k arR = new k("interstitialAdActivityOpt", 0);
    public static k arS = new k("formAdExitInterceptSwitch", 0);
    public static k arT = new k("adLeaveConfirmSwitch", 0);
    public static k arU = new k("viewLandingPageTaskDuration", 15);
    public static k arV = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d arW = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static n arX = new n("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d arY = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d arZ = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d asa = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static k asb = new k("commercialLoggerSwitch", 1);
    public static q asc = new q("tkSoUrlV7a", "");
    public static q asd = new q("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d ase = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static l asf = new l("playerConfig", null);
    public static r asg = new r("pkgNameList", new ArrayList(0));
    public static r ash = new r("hostList", new ArrayList(0));
    public static r asi = new r("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem asj = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c ask = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem asl = new InstallActivateReminderConfigItem();
    public static e asm = new e();
    public static o asn = new o("realtimeReportActions", "");
    public static p aso = new p();
    public static k asp = new k("appInstallNoticeSecond", 0);
    public static k asq = new k("installFloatingLayerPostion", 0);
    public static k asr = new k("remindInstallStyle", 0);
    public static k ass = new k("remindInstallTime", 60);
    public static k ast = new k("watermarkKwaiIdSwitch", 0);
    public static k asu = new k("insertScreenV2Switch", 0);
    public static k asv = new k("insertScreenAutoPlaySwitch", 0);
    public static j asw = new j("insertScreenV2ShowConfig");
    public static k asx = new k("environmentDetectEnable", 0);
    public static k asy = new k("simCardInfoEnable", 0);
    public static k asz = new k("baseStationEnable", 0);
    public static k asA = new k("sensorEventEnable2", 0);
    public static k asB = new k("lpAutoDownloadApkSwitch", 1);
    public static k asC = new k("autoDownloadUrlSwitch", 0);
    public static k asD = new k("insertScreenAdType", 0);
    public static k asE = new k("interstitialAutoCallAppCountDaily", 1);
    public static k asF = new k("mediaControlPlaySwitch", 1);
    public static q asG = new q("appStatusSoUrlV7a", "");
    public static q asH = new q("appStatusSoUrlV8a", "");
    public static q asI = new q("appStatusSoVersion", "");
    public static k asJ = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d asK = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h asL = new h();
    public static com.kwad.sdk.core.config.item.d asM = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d asN = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static com.kwad.sdk.core.config.item.d asO = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d asP = new com.kwad.sdk.core.config.item.d("TKJsonSubThread", true);
    public static com.kwad.sdk.core.config.item.d asQ = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d asR = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k asS = new k("forceActivate", 0);
    public static k asT = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d asU = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static q asV = new q("nativeAndAnrDynamic", "");
    public static k asW = new k("kwaiAppVersionSwitch", 1);
    public static q asX = new q(TTDownloadField.TT_USERAGENT, com.kwad.sdk.core.network.p.getDefaultUserAgent());
    public static k asY = new k("biddingLogSwitch", 0);
    public static k asZ = new k("forceActiveThreshold", 5);
    public static k ata = new k("forceActiveInterval", 3);
    public static k atb = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d atc = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g atd = new g("adExposureAreaPercent", 0.3f);
    public static g ate = new g("adExposureTime", -1.0f);
    public static g atf = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d atg = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d ath = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k ati = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d atj = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static k atk = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d atl = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d atm = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static n atn = new n("obiwanLogFilesDiskQuota", 52428800L);
    public static l ato = new l("logCommandResult", "", false);
    public static n atp = new n("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d atq = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static k atr = new k("playableAutoPlayEnable", 1);
    public static k ats = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d att = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d atu = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k atv = new k("weaponSwitch", 1);
    public static k atw = new k("kvModeV2", 0);
    public static i atx = new i();
    public static k aty = new k("idcRollbackInterval", 0);
    public static n atz = new n("currentServerTimeMs");
    public static k atA = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g atB = new g("adTraceReportRate", 1.0f);
    public static k atC = new k("adTraceRepeatEnable", 0);
    public static k atD = new k("appHeartBeatInterval", 0);
    public static k atE = new k("insertShowPercent", 100);
    public static k atF = new k("adCacheCode", 0);
    public static q atG = new q("installTipsContentDesc", "");
    public static q atH = new q("installTipsPositiveActionDesc", "");
    public static q atI = new q("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d atJ = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static q atK = new q("perfMonitorV2", "");
    public static k atL = new k("neoVideoAdaptStrategy", 1);
    public static k atM = new k("feedTKLoadTimeOut", 2500);
    public static com.kwad.sdk.core.config.item.d atN = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static k atO = new k("adImageLoaderCacheLimitSize", -1);
    public static com.kwad.sdk.core.config.item.d atP = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static k atQ = new k("videoCacheOpt", 0);
    public static q atR = new q("ranger", "");
    public static q atS = new q("eplV1", "");
    public static q atT = new q("threadPoolPerfMonitor", "");
    public static q atU = new q("threadPoolParams", "");
    public static f atV = new f("crashUploadRate", Double.valueOf(1.0d));
    public static f atW = new f("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d atX = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d atY = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d atZ = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d aua = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d aub = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d auc = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d aud = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static k aue = new k("tubeRenderType", 0);
    public static k auf = new k("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d aug = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static q auh = new q("trackBlackUrlConfig", "");
    public static k aui = new k("tkMemCacheSize", 0);
    public static r auj = new r("preloadMemCacheTemplateIds", new ArrayList(0));
    public static k auk = new k("kGeoInfoConfig", 1);
    public static k aul = new k("appMonitorSwitch", 0);
    public static k aum = new k("videoCacheErrorCallbackSwitch", 0);
    public static k aun = new k("tkErrorDetailCount", 1);
    public static k auo = new k("videoLaunchOptimiseSwitch", 0);
    public static k aup = new k("enableInitStartMode", 1);
    public static q auq = new q("localLogConfig", "");
    public static q aur = new q("adLogRetryConfig", "");
    public static m aus = new m("dpSchemeFlags");

    public static void init() {
    }
}
